import turtle as t

house = t.Turtle()
wn = t.Screen()

wn.setup(800, 800)
house.speed(1)
house.hideturtle()

def drawHouse():
    house.fillcolor("darkorchid4")
    house.begin_fill()
    house.penup()
    house.goto(-200, -150)
    house.pendown()
    house.goto(200, -150)
    house.goto(200, 150)
    house.goto(-200, 150)
    house.goto(-200, -150)
    house.end_fill()

def drawRoof():
    house.fillcolor("lightblue")
    house.begin_fill()
    house.penup()
    house.goto(-250, 150)
    house.pendown()
    house.goto(250, 150)
    house.goto(0, 250)
    house.goto(-250, 150)
    house.end_fill()

def drawDoor():
    house.fillcolor("red")
    house.begin_fill()
    house.penup()
    house.goto(170, -150)
    house.pendown()
    house.goto(170, -50)
    house.goto(120, -50)
    house.goto(120, -150)
    house.goto(170, -150)
    house.end_fill()
    house.fillcolor("black")
    house.begin_fill()
    house.penup()
    house.goto(132, -110)
    house.pendown()
    house.circle(2)
    house.end_fill()

def drawWindow():
    house.fillcolor("darkgrey")
    house.begin_fill()
    house.penup()
    house.goto(-150, 0)
    house.pendown()
    house.goto(-90, 0)
    house.goto(-90, -60)
    house.goto(-150, -60)
    house.goto(-150, 0)
    house.end_fill()
    house.penup()
    house.goto(-120, -60)
    house.pendown()
    house.goto(-120, 0)
    house.penup()
    house.goto(-150, -30)
    house.pendown()
    house.goto(-90, -30)
    house.end_fill

def drawTree():
    house.fillcolor("brown")
    house.begin_fill()
    house.penup()
    house.goto(-325, -150)
    house.pendown()
    house.goto(-340, -150)
    house.goto(-340, -50)
    house.goto(-325, -50)
    house.goto(-325, -150)
    house.end_fill()
    house.penup()
    house.goto(-332, -50)
    house.fillcolor("green")
    house.begin_fill()
    house.pendown()
    house.circle(50)
    house.end_fill()


drawHouse()
drawRoof()
drawDoor()
drawWindow()
drawTree()

t.exitonclick()